### ISSUE TITLE
ReferenceError: strXmlBullet is not defined  

### ISSUE THREAD

**Issue by Saurabh-Chandil** [gitbrent/PptxGenJS#587] opened 2019-09-08 07:30 UTC
Hi Brent,

I have just make npm install pptxgenjs and put following code in ts file : 
    import * as pptGen from 'pptxgenjs';

    const pptx = new pptGen();
    const slide = pptx.addNewSlide();
    slide.addText('Image Path!', { x: 1.5, y: 1.5, font_size: 18, color: '363636' });
    pptx.save('Sample Presentation');

I tried to solve this strXmlBullet error in every possible way but couldn't resolve that and every time this same error is coming.
![strXmlBullet](https://user-images.githubusercontent.com/19798633/64485034-96b5a900-d238-11e9-9333-a1be333fc71c.PNG)

**Comment by gitbrent** [comment] 2019-09-08 21:20
Hi @Saurabh-Chandil 

Thanks for reporting this.  The issue is fixed in the master branch.

Note that the next major release, `3.0` is written in typescript and many of the issues like these have already been resolved.

**Closed** 2019-09-08 21:21 UTC
Labels: bug
