### ISSUE TITLE
breakLine not behaving correctly when "align" property set in .addText?

### ISSUE THREAD

**Issue by Slidemagic** [gitbrent/PptxGenJS#751] opened 2020-05-26 10:32 UTC
I am parsing HTML strings with bold tags to make them appear in PowerPoint.

For some reason, the breakLine property does not work when the 'align' property is set in a call to .addText. Line breaks are introduced after every element of the text snippet array. Removing the 'align' property makes it work again, but the text is moved to the left as a result. (Trial and error from my side)

It is still a bit hard to find the issue myself, maybe it is somewhere around these lines in the screen shot.

Mystery 😄 

<img width="1159" alt="Screenshot 2020-05-26 13 25 37" src="https://user-images.githubusercontent.com/5433253/82890543-0994ba80-9f55-11ea-8403-ebd3f8cc8e89.png">

**Comment by gitbrent** [comment] 2020-05-28 04:28
Similar Issues: #369 #448 #460

Working on this issue for v3.3.0

**Comment by Slidemagic** [comment] 2020-05-28 05:14
Thank you!

**Comment by ReimaFrgos** [comment] 2020-06-15 02:01
@gitbrent have you started on this one at all? I did some local testing and t looks like two small changes resolve the issue, without any side effects in my decks. Haven't run through a test suite yet.

Modify (around line 2420):
`else if (idx > 0 && (typeof textObj.options.bullet !== 'undefined' || typeof textObj.options.align !== 'undefined')) {`
`else if (idx > 0 && (typeof textObj.options.bullet !== 'undefined' )) {`

The alignment seems to happen on the first alignment it hits though, so modifying to reverse the sequence (around line 2405):
`textObj.options.align = textObj.options.align || opts.align;`
to
`textObj.options.align = opts.align || textObj.options.align;`
Keeps it to the alignment set for the main object rather than an individual line within the text block.

**Comment by gitbrent** [comment] 2020-06-16 04:01
@ReimaFrgos - I actually have not started as of yet, so thanks a ton for looking more closely at this.

I'll start on this very shortly and report back...

**Comment by brandonkal** [comment] 2020-06-17 18:46
I've managed to fix this. Would you like a PR @gitbrent or are you on this?

**Comment by gitbrent** [comment] 2020-06-22 01:47
The entire text generation method has been rewritten should be rock solid from here out.

Fixes: [\#369](https://github.com/gitbrent/PptxGenJS/issues/369), [\#448](https://github.com/gitbrent/PptxGenJS/issues/448), [\#460](https://github.com/gitbrent/PptxGenJS/issues/460), [\#751](https://github.com/gitbrent/PptxGenJS/issues/751), [\#772](https://github.com/gitbrent/PptxGenJS/pull/772)

Some collected test cases:
```javascript
var pptx = new PptxGenJS();
var slide = pptx.addSlide();

slide.addText(
    [
        { text: "line 1: 1st word ", options: { fontSize: 24, color: "99ABCC" } },
        { text: "2nd word ", options: { fontSize: 36, color: "FFFF00" } },
        { text: "3rd word ", options: { fontSize: 48, color: "0088CC" } },
    ],
    { x: 1.5, y: 0.3, w: 7, h: 1, margin: 0.1, fill: "232323" }
);

slide.addText(
    [
        { text: "line 1: 1st word ", options: { color: "99ABCC", italic: true } },
        { text: "2nd word ", options: { color: "FFFF00", bold: true } },
        { text: "3rd word ", options: { color: "0088CC" } },
    ],
    { x: 1.5, y: 1.6, w: 7, h: 1, margin: 0.1, fill: "232323", align: "center" }
);

slide.addText(
    [
        { text: "line 1: 1st word ", options: { color: "99ABCC", align: "center" } },
        { text: "2nd word ", options: { color: "FFFF00", align: "center" } },
        { text: "3rd word ", options: { color: "0088CC", align: "center" } },
    ],
    { x: 1.5, y: 2.9, w: 7, h: 1, margin: 0.1, fill: "336699" }
);

slide.addText(
    [
        { text: "line 1: 1st word ", options: { color: "99ABCC", align: "left" } },
        { text: "line 2: 1st word ", options: { color: "FFFF00", align: "center" } },
        { text: "2nd word ", options: { color: "0088CC", align: "center", breakLine: true } },
        { text: "\nline 4: 1st word", options: { color: "0088CC", align: "center" } },
    ],
    { x: 1.5, y: 4.2, w: 7, h: 1.3, margin: 0.1, fill: "224466" }
);

pptx.writeFile("PptxGenJS-TextRuns");
```

Results:
<img width="1134" alt="Screen Shot 2020-06-21 at 20 43 48" src="https://user-images.githubusercontent.com/7218970/85241050-109dd400-b400-11ea-9384-cdc011741e11.png">

@brandonkal @Slidemagic @ReimaFrgos @ellisgl 
If you have any breaking test cases, please provide them.

**Comment by ReimaFrgos** [comment] 2020-07-01 06:31
@gitbrent I've run the latest beta against all my decks and all works succesfully for me.

**Comment by gitbrent** [comment] 2020-07-02 03:27
@ReimaFrgos - thanks!

Closing for inclusion in v3.3.0. If anyone else finds a breaking test case, please provide it.

**Closed by gitbrent** 2020-07-02 03:27 UTC
Labels: text

**Comment by sandeep-pamujula** [comment] 2020-08-11 12:50
Hi @gitbrent,  Hope align right for multiple words would result in single line with v3.3.0 release

**Comment by brandonkal** [comment] 2020-09-01 02:59
@gitbrent 
Now that the update has been released, I have tested it and have some breaking cases (3.3.1):

This input (centered):
///
R. **Bolded text**

Line 1
Line 2

R. **Bolded text**
////

Prints as
///
R.
**Bolded text**


Line 1 (notice extra line before and after bolded text)
Line 2

R.
**Bolded text**
////

Case 2:
////
Line 1
Line 2
Line 3

Line 5
**Bolded Line 6**
////
Prints as
////
Line 1
Line 2
Line 3

Line 5

**Bolded Line 7**
////

**Comment by gitbrent** [comment] 2020-09-01 04:59
@brandonkal - I’ll need to see the code and the output, similar to my update on Jun 21

**Comment by brandonkal** [comment] 2020-09-01 08:44
@gitbrent:
Test cases provided. See linked PR #839. I'd like to see that as part of the test suite to avoid a regression here.

Thank you!

**Comment by gitbrent** [comment] 2020-09-02 01:20
@brandonkal - thanks for the PR. The `demos.js` file has 4400 diffs, can you just add the new test code here?

**Comment by brandonkal** [comment] 2020-09-02 02:06
Run prettier on the file and you'll see the diff is much smaller.

The file wasn't formatted to your style.

If you look at the PR, the prettier run is in its own commit to make review easy.
