### ISSUE TITLE
Margin not working with placeholder text (v3)

### ISSUE THREAD

**Issue by bestis** [gitbrent/PptxGenJS#640] opened 2020-01-07 08:11 UTC
Hi,

This used to work:
defineSlideMaster having object:
```javascript
{
	placeholder: {
		options: {
			name: "title",
			type: "title",
			x: leftMargin,
			y: 0.2,
			w: layoutWidth - leftMargin - logoWidth,
			h: 0.3,
			bold: true,
			fontFace: "Helvetica",
			color: "404040",
			fontSize: 18,
			align: "left",
			valign: "middle",
			margin: 0,
		},
		text: "",
	},
},
```
And then adding to it.
```javascript
imageSlide.addText(slideTitle, {
	placeholder: "title",
});
```

Some screenshots to visualize the problem:

Old version:
![title-has-no-margin-v2](https://user-images.githubusercontent.com/1753286/71878954-97524380-3135-11ea-8248-d005b59974b6.png)
New version:
![title-has-margin-v3](https://user-images.githubusercontent.com/1753286/71878955-97eada00-3135-11ea-9456-1ee716b210f1.png)
And settings:
![title-has-margins-v3](https://user-images.githubusercontent.com/1753286/71878951-97524380-3135-11ea-89c5-e3e7c5cdd7d0.png)

Tested with https://github.com/gitbrent/PptxGenJS.git#2cee3f0c412106aefb1f87fc16bfef78ae5521a7 (as it solved the JSZip problem).

**Comment by bestis** [comment] 2020-01-07 08:36
Oh and just noticed that the "Vertical alignment" is not working either. As we can see on the screenshot it's "Top", but I did specify it as "middle".

**Comment by GodsBest** [comment] 2020-03-19 18:08
Yes, I can confirm too that “vertical alignment” is not working. The default is `top`; setting `valign=“bottom”` or `valign=“middle”` does not change the alignment.

**Comment by ReimaFrgos** [comment] 2020-07-07 15:26
@gitbrent looks like there's a logic issue in`function genXmlBodyProperties(slideObject)`

The first if statement block sets the anchor attribute for text objects to control vertical alignment, but Placeholders are being sent to the else block which doesn't set the anchor in bodyProperties.

**Comment by eddy-lau** [comment] 2021-01-05 09:35
Is the `valigin` problem fixed?

**Comment by eddy-lau** [comment] 2021-01-05 09:47
> Is the `valigin` problem fixed? I got the same issue when adding placeholder.

I confirmed that the latest 3.4.0 still has this issue.

**Comment by gitbrent** [comment] 2021-04-17 21:31
Thanks for reporting this @bestis 

Fixed in newest build, targeted to v3.6.0

```typescript
let pptx = new PptxGenJS();
pptx.defineSlideMaster({
    title: "MASTER_SLIDE",
    background: { fill: "F1F1F1" },
    margin: [0.5, 0.25, 1.0, 0.25],
    objects: [
        {
            placeholder: {
                options: {
                    name: "header",
                    type: "title",
                    x: 0.6,
                    y: 0.2,
                    w: 6,
                    h: 1.0,
                    color: "696969",
                    fontSize: 18,
                    align: "left",
                    valign: "middle",
                    margin: 0,
                },
                text: "",
            },
        },
        {
            placeholder: {
                options: {
                    name: "title",
                    type: "title",
                    x: 0.6,
                    y: 2.2,
                    w: 6,
                    h: 1.0,
                    color: "404040",
                    fontSize: 18,
                    align: "right",
                    valign: "bottom",
                    margin: 0,
                },
                text: "METOO",
            },
        },
    ],
});

let slide = pptx.addSlide("MASTER_SLIDE");

pptx.writeFile({ fileName: "PptxGenJS-Sandbox.pptx" });
```

![Screen Shot 2021-04-17 at 16 27 07](https://user-images.githubusercontent.com/7218970/115127208-57b21280-9f9a-11eb-9230-dc972a8bc1fa.png)

**Closed by gitbrent** 2021-04-17 21:31 UTC
Labels: issue:bug

**Comment by mikemeerschaert** [comment] 2023-04-26 18:05
Sorry but I don't think this is working anymore. I just tested on v3.12.0 and noticed that neither valign nor margin are being respected in the placeholders.

![image](https://user-images.githubusercontent.com/2775912/234664295-605083c8-4194-4b3b-8f8b-c0640accece8.png)

I think this is because of this line of code: https://github.com/gitbrent/PptxGenJS/blob/5a30b0f5c75a1b7495202155064e5b8595ecf8f8/src/gen-objects.ts#L1013

You're checking if `target._slideLayout` exists, which will never be true, because of how the master slides are created.

The above referenced code is in the `addTextDefinition` method, which is called by `createSlideMaster`, which passes through the target that is created in the `defineSlideMaster` method, which defines the `layout` like so before passing it as the `target`.

```TypeScript
const newLayout: SlideLayout = {
	_margin: props.margin || DEF_SLIDE_MARGIN_IN,
	_name: props.title,
	_presLayout: this.presLayout,
	_rels: [],
	_relsChart: [],
	_relsMedia: [],
	_slide: null,
	_slideNum: 1000 + this.slideLayouts.length + 1,
	_slideNumberProps: props.slideNumber || null,
	_slideObjects: [],
	background: props.background || null,
	bkgd: props.bkgd || null,
}
```

As far as I can tell, `_slideLayout` never gets defined, so that block of code referenced above will never return true for master slides, and the `valign` and `margin` will never be applied.

I can look into making a PR to fix this, I also noticed bullet's `characterCodes' aren't respected in placeholders either so I'll see if I can figure out how to fix that issue as well (although that's a separate issue)

**Comment by jandobrx** [comment] 2025-06-08 01:28
This last patch is a god send for fixing the margins. @mikemeerschaert 

If your lazy like me and using ^4.0.0 you can hot patch : pptxgen.cjs.js file

line # 6007

https://github.com/gitbrent/PptxGenJS/pull/1247/commits/bab340ebe5f0484feb5bda94b3bb930e30513fe3

and the valign issue will be fixed

This should 150% be in the repo
