### ISSUE TITLE
Not Able to change Radar chart line colors

### ISSUE THREAD

**Issue by ankush-uipath-13** [gitbrent/PptxGenJS#1057] opened 2022-02-01 04:24 UTC
I couldn't find a way to change line colors for radar charts. 
chartColors property, only change the data points colors, but the line colors remains the same.
![radar](https://user-images.githubusercontent.com/82217330/151912587-f787aece-9f12-4573-ad4a-50b5f9992274.png)

**Comment by gitbrent** [comment] 2022-02-20 21:58
Duplicate of Issue #539

**Closed by gitbrent** 2022-02-20 21:58 UTC
