### ISSUE TITLE
[BUG] Setting highlight to one of the TextProps items makes rest of the elements also highlighted

### ISSUE THREAD

**Issue by mert-iskender** [gitbrent/PptxGenJS#1063] opened 2022-02-14 08:56 UTC
library version: [ 3.9.0 ]
When using `slide.addText(text: string | TextProps[], options?: TextPropsOptions): Slide` method with list of `TextProps` items, if one of the items has highlight property set, the rest of the items in the list also inherits this value somehow.
```
       const text = [
            {
                text: "Regular ",
                options: {
                  fontFace: "Calibri",
                  fontSize: 12,
                },
              },
            {
              text: "highlighted",
              options: {
                highlight: "FFFF00",
                fontFace: "Calibri",
                fontSize: 12,
              },
            },
            {
              text: " Regular",
              options: {
                fontFace: "Calibri",
                fontSize: 12,
              },
            },
        ]
        slide.addText(text, { x: '5%', h: '20%' });
```
the output looks like
![Screenshot from 2022-02-14 11-50-54](https://user-images.githubusercontent.com/58942189/153830771-55537406-68f6-4a4a-a54f-0f13a5705def.png)

If I specifically override the rest of the items with white color highlight then it produce the desired output

 ```
       const text = [
            {
                text: "Regular ",
                options: {
                  fontFace: "Calibri",
                  fontSize: 12,
                },
              },
            {
              text: "highlighted",
              options: {
                highlight: "FFFF00",
                fontFace: "Calibri",
                fontSize: 12,
              },
            },
            {
              text: " Regular",
              options: {
                highlight: "FFFFFF",       // adding this fixes this text's appereance
                fontFace: "Calibri",
                fontSize: 12,
              },
            },
        ]
        slide.addText(text, { x: '5%', h: '20%' });
```
![Screenshot from 2022-02-14 11-53-24](https://user-images.githubusercontent.com/58942189/153831171-0ae719e2-ec7f-405e-88d4-5b181faf0718.png)

**Comment by gitbrent** [comment] 2022-02-19 19:10
I'm unable to reproduce this:

```javascript
let pptx = new PptxGenJS();
let slide = pptx.addSlide();

const text = [
    {
        text: "Regular ",
        options: {
            fontFace: "Calibri",
            fontSize: 12,
        },
    },
    {
        text: "highlighted",
        options: {
            highlight: "FFFF00",
            fontFace: "Calibri",
            fontSize: 12,
        },
    },
    {
        text: " Regular",
        options: {
            fontFace: "Calibri",
            fontSize: 12,
        },
    },
];
slide.addText(text, { x: "5%", h: "20%" });
pptx.writeFile({ fileName: "PptxGenJS-Sandbox.pptx" });
```
![Screen Shot 2022-02-19 at 13 08 43](https://user-images.githubusercontent.com/7218970/154815396-baa472df-9fa3-41f7-a148-38e76a72fe24.png)

**Comment by mert-iskender** [comment] 2022-02-22 07:20
I am using version 3.9.0 in a node.js application. Are you using an unreleased version or did you tested in node app?

**Comment by gitbrent** [comment] 2022-02-24 00:58
I'm unsure why you're getting that result.

The v3.9.0 library in the [online demo](https://gitbrent.github.io/PptxGenJS/demo/browser/index.html#shapes) produces a correct highlighted text sample.

**Comment by gitbrent** [comment] 2022-05-25 03:22
(Closing due to age)

**Comment by gitbrent** [comment] 2022-05-25 03:22
(Closing due to age)

**Closed by gitbrent** 2022-05-25 03:22 UTC
Labels: triage:cannot-reproduce
