### ISSUE TITLE
Presentation opens needing repair in PowerPoint 2007 (works in other versions)

### ISSUE THREAD

**Issue by gregdolley** [gitbrent/PptxGenJS#241] opened 2017-11-16 05:27 UTC
The font_face attribute doesn't work when running the pptx generator via NodeJS, but works fine when running in plain javascript on a web page. Here's a simple node example:

let pptx = require('pptxgenjs');
let slide = pptx.addNewSlide();
slide.addText('Hello World!', { font_face: "Arial", x:1.5, y:1.5, font_size:18, color:'363636' });
pptx.save('Sample Presentation');

I used Arial font, but you could use "Gothic" like in this web page example that has almost identical code: https://codepen.io/KingsRansom/pen/qrBXRe

The file generated from the node version is corrupt, but the one generated from the codepen example opens just fine.

Any ideas??? I've tried googling this for hours.  Please help!

**Comment by gitbrent** [comment] 2017-11-16 18:41
Hi @gregdolley,

I'm not sure what the issue is with the fonts.

The node-demo under `examples` works just fine and generates various fonts without issue:

```
[brent@MacbookAir 12:36:38] ~/Documents/GitHub/PptxGenJS/examples 
=> node nodejs-demo.js 

-------------
STARTING DEMO
-------------
 * pptxgenjs version: 1.11.0-beta.20171115
```

![screen shot 2017-11-16 at 12 39 57](https://user-images.githubusercontent.com/7218970/32909132-5f36412c-cacb-11e7-8ed3-e24620e43f2e.png)

**Comment by gregdolley** [comment] 2017-11-17 22:11
After some experimentation, we found out that it is just older versions of Office which can't open the PowerPoint. I tried in Office 2007. If you run your example above, and try to open the file in PowerPoint 2007, you'll get an error (but generating the file from the codepen will create a file that CAN be opened with PowerPoint 2007). So there must be some difference in the nodeJS version and whatever is being run in the javascript of the codepen. Any ideas??

**Comment by gitbrent** [comment] 2017-11-20 15:56
Hi @gregdolley,

I do not know off-hand why this would be the case.  The presentation XML is the same - the only difference in Node vs browser is how they are saved.

PowerPoint 2007 isn't something I have access to, so i'm unable to test the output to see what the diff may be.

**Comment by gitbrent** [comment] 2017-11-22 23:27
Hi @gregdolley @gauravjain024,

Could you generate a Presentation in PPT 2007 and add it here so i could analyze it?

Just a simple slide with text would be fine, assuming that this is enough to reproduce the issue:
```javascript
var pptx = new PptxGenJS();
var slide = pptx.addNewSlide();
slide.addText('Issue-241', {x:1, y:1, w:6, h:2, fill:'FFFCCC'} );
pptx.save('PptxGenJS-Issue-241');
```
![screen shot 2017-11-22 at 17 25 18](https://user-images.githubusercontent.com/7218970/33153876-2dfe37e8-cfaa-11e7-944c-e5a1257b4158.png)

**Comment by gitbrent** [comment] 2017-11-25 21:37
Hi @gregdolley @gauravjain024,

I've made quite a few updates in the past few days to sync the output of the PPT to what the PowerPoint app produces.

Try the library with PowerPoint 2007 again if you would and let me know if the issue still exists.

Thanks!

**Comment by gitbrent** [comment] 2017-12-06 03:41
It would be helpful to have something to compare the current output against.

If anyone could create a simple "hello world" presentation using PowerPoint 2007 and upload it here, I would appreciate it.

**Comment by timh1004** [comment] 2017-12-06 14:49
There you go:
[PowerPoint 2007.pptx](https://github.com/gitbrent/PptxGenJS/files/1535535/PowerPoint.2007.pptx)
Thank you!

**Comment by gitbrent** [comment] 2018-01-01 22:11
Hi All,

I've compared the library output to the PowerPoint 2007 example and made some changes.

If anyone could test with 2007 and let me know what the result is, i'd appreciate it.

**Comment by StefanBrand** [comment] 2018-11-30 23:12
I just tested with the 2.4.0 release and I get an error message when I open (or download and open) the "Basic Slide Demo". Otherwise the presentation works fine when I click "yes" in the error message. 

![grafik](https://user-images.githubusercontent.com/8948865/49319453-4bc67280-f4fd-11e8-84a6-6e6282dbcd9c.png)

![grafik](https://user-images.githubusercontent.com/8948865/49319470-5aad2500-f4fd-11e8-8961-7636e98061a3.png)

When I save the file with Office 2007 and open it again, no error message appears. Attaching both versions:

- [PptxGenJs-Basic-Slide-Demo_new.pptx (43KB)](https://github.com/gitbrent/PptxGenJS/files/2635258/PptxGenJs-Basic-Slide-Demo_new.pptx) (directly after downloading)
- [PptxGenJs-Basic-Slide-Demo_saved.pptx (16KB)](https://github.com/gitbrent/PptxGenJS/files/2635262/PptxGenJs-Basic-Slide-Demo_saved.pptx) (after saving with Powerpoint 2007)

**Comment by gitbrent** [comment] 2020-01-14 05:05
Closing due to age.

**Closed by gitbrent** 2020-01-14 05:05 UTC
Labels: help-wanted, legacy-versions, question

**Comment by kritarth2121** [comment] 2024-02-08 13:18
Facing the same problem now, with Powerpoint 2021

**Comment by RaghavShubham** [comment] 2025-06-27 10:42
Still getting this error

**Comment by gitbrent** [comment] 2025-06-29 21:08
### To Those Arriving Here from Search Engines

Please visit the [needs repair errors troubleshooting guide](https://gitbrent.github.io/PptxGenJS/docs/needs-repair-errors/) for more information.
