### ISSUE TITLE
Vertical align and line break bug since update

### ISSUE THREAD

**Issue by mirkoint** [gitbrent/PptxGenJS#79] opened 2017-05-04 12:28 UTC
Hey there,

since the last update options like valign, align and margin don't work anymore for a text element with multiple styles like here:

`slide.addText(
  [
    { text: 'Lorem', options: { bold: true, breakLine: true } },
    { text: description }
  ],
   { x: 0, y: 0, w: 2, h: 2, valign: 'middle', margin: 0 }
)`

Valign, align and margin will be default this way.

**Comment by ZouhaierSebri** [comment] 2017-06-01 07:46
Hi @gitbrent ,

why line 1503 and 1504 commented.
when we remove comment we get the expected result.

**Comment by mirkoint** [comment] 2017-06-16 10:16
@ZouhaierSebri do you mean [this one?](https://github.com/gitbrent/PptxGenJS/blob/master/dist/pptxgen.js#L1500-L1501) It makes the valign work again 👍 
Any idea how do fix the margin as well?

**Comment by ZouhaierSebri** [comment] 2017-06-19 07:33
Hi @mirkoint ,
yes 
`textObj.options.bodyProp = ( textObj.options.bodyProp || {} );
textObj.options.bodyProp.anchor = ( textObj.options.valign || slideObj.options.valign );`

**Comment by mirkoint** [comment] 2017-06-19 08:33
But it only vixes the valign. I'm also trying to fix the margin. Any idea @ZouhaierSebri ?

**Comment by mirkoint** [comment] 2017-08-25 14:13
Hey @gitbrent,
when do you think this bug will be fixed? :)
Cheers,
Mirko

**Comment by Szymon-dziewonski** [comment] 2017-09-14 10:08
yes I'm signing in to this question too :) where it will be fixed ?

Thanks

**Comment by gitbrent** [comment] 2017-09-15 04:40
Hi @mirkoint @ZouhaierSebri @Szymon-dziewonski ,

Initially, I was vexed by this as having more than 1 align tag in a paragraph was causing issues in PowerPoint 2007, so i was hesitant and didn't to trade one issue for another.  After spending months on Charts, i'm glad you all reminded me to re-engage on this one.

Turns out it was just a good old fashioned bug where i was placing a properties tag inside the wrong XML parent tag and it was getting tangled up.  I've fixed in the current codebase - both `valign` and `margin` behave as intended.

Try it out now and let me know what you think.  Example below.

```javascript
var pptx = new PptxGenJS();
var slide = pptx.addNewSlide();

slide.addText(
  [
    { text:'Text from', options:{ bold:true, breakLine:true } },
    { text:'Issue #79' }
  ],
  { x:0, y:0, w:2, h:2, valign:'middle', margin:0, line:'0088CC', fill:'F1F1F1' }
);

pptx.save('PptxGenJS-Issue79');
```
![screen shot 2017-09-14 at 23 32 29](https://user-images.githubusercontent.com/7218970/30466692-37a18af6-99a5-11e7-8363-eff4bd31e596.png)

**Comment by Szymon-dziewonski** [comment] 2017-09-15 06:27
Hello @gitbrent , Thank you for respond, by the way great job, is there any way to donate you few "bucks"? :)
As for margins and valign its not working for me 

` description_table.addText([{
      text: 'General information:',
      options: {x: 0.4, y: 0.2, font_size: 27, font_face: calibri, color: new_light_blue}
    }], {x: 0.6, y: 0.3, h: 0.6, margin: 0, valign: "middle"});`

and heres result 
![image](https://user-images.githubusercontent.com/2566152/30469252-a41d49aa-99ef-11e7-9cbf-d225571b0269.png)

**Comment by mirkoint** [comment] 2017-09-15 10:19
Awesome @gitbrent, thank you so much!

**Comment by gitbrent** [comment] 2017-09-15 22:44
@Szymon-dziewonski - thanks!

If you want to support the project, put a link to the GitHub site on your social network. :-)

**Closed by gitbrent** 2017-09-15 22:44 UTC
Labels: bug
