### ISSUE TITLE
Align and line break bug

### ISSUE THREAD

**Issue by evamansilla** [gitbrent/PptxGenJS#689] opened 2020-02-27 10:51 UTC
I need something similar inside a rectangle:
![image](https://user-images.githubusercontent.com/61541758/75434892-87dfc180-5952-11ea-9a55-3276f32fb854.png)

So, I have this code: 
```
      slide.addText(
        [
          { text: 'Line1', options: {breakLine:false} },
          { text: 'Line 2', options: {bold:true} },
        ], 
        {shape: pptx.ShapeType.RECTANGLE, h:1.127, w:1.951, fill:'e5ebef', x:3.778, y:6.911, color:'000000', fontFace:'Arial', fontSize:8, align: 'center', valign:'top'}
      );
```
and the result I get is:
![image](https://user-images.githubusercontent.com/61541758/75435563-82cf4200-5953-11ea-9e16-e2c862cf2a17.png)

By removing the align option:
```

      slide.addText(
        [
          { text: 'Line1', options: {breakLine:false} },
          { text: 'Line 2', options: {bold:true} },
        ], 
        {shape: pptx.ShapeType.RECTANGLE, h:1.127, w:1.951, fill:'e5ebef', x:3.778, y:6.911, color:'000000', fontFace:'Arial', fontSize:8, valign:'top'}
      );
```
the  new result is:
![image](https://user-images.githubusercontent.com/61541758/75437820-266e2180-5957-11ea-9a3f-c0a47f9525eb.png)
and if I set align option to the left, I get again a line break:
![image](https://user-images.githubusercontent.com/61541758/75437887-3e45a580-5957-11ea-92f9-f49b075ca76d.png)

**Comment by gitbrent** [comment] 2020-03-04 05:07
@evamansilla Thanks for the fine documentation and examples.

Closing as this is a dupe of Issue #369

**Closed by gitbrent** 2020-03-04 05:07 UTC
Labels: text
