### ISSUE TITLE
Enable catAxisLabelPos to be set to 'none'

### ISSUE THREAD

**Issue by Slidemagic** [gitbrent/PptxGenJS#476] opened 2019-01-14 16:01 UTC
This renders the Axis line, but not the labels. It should be a minor tweak around line 3520 in the code, 'none' is a standard option that PowerPoint will eat, next to 'high', 'low', 'nextTo'.

I like to control the chart axis labels myself using regular PowerPoint shapes, rather than using the Excel chart engine for this.

For my own use, I hard coded the change for the moment.

**Comment by ReimaFrgos** [comment] 2019-01-16 16:40
This looks like a straight forward change:

`strXml += '  <c:tickLblPos val="'+ (opts.catAxisLabelPos || opts.barDir == 'col' ? 'low' : 'nextTo') +'"/>';`

update to:
`strXml += '  <c:tickLblPos val="'+ (opts.catAxisLabelPos || (opts.barDir == 'col' ? 'low' : 'nextTo')) +'"/>';`

The existing logic is validating as: 
If this option is specified, or it's a column graph then set it to 'low'. 
Otherwise set it to 'nextTo'.

Updating the parenthesis, correctly accepts any valid attribute including none.

I've tested on the example site and confirmed. I can submit a PR this week, as there's one or two other points with similar logic to check first.

**Comment by Slidemagic** [comment] 2019-01-17 06:04
> I can submit a PR this week, as there's one or two other points with similar logic to check first.

Perfect, thank you. I will follow and learn how to do these type of things.

**Comment by ReimaFrgos** [comment] 2019-01-22 05:20
Have submitted PR #482 to resolve this for each of the Axis settings and validate for legitimate input.

**Comment by gitbrent** [comment] 2020-03-04 04:51
Closing as Pull is complete.

**Closed by gitbrent** 2020-03-04 04:51 UTC
Labels: enhancement-chart
