### ISSUE TITLE
Presentation opens needing repair if i add image with url ? 

### ISSUE THREAD

**Issue by TMBeliever** [gitbrent/PptxGenJS#592] opened 2019-09-19 07:43 UTC
Presentation opens needing repair if i add image with url ?

**Comment by gitbrent** [comment] 2019-09-21 03:08
The issue is likely fixed in the new 3.0 branch - several URL parsing bugs are coming in the next release.

If you test the URL in the new codebase and there's still an issue, let me know.

**Comment by gitbrent** [comment] 2020-02-28 05:28
[Closing due to age]

**Closed by gitbrent** 2020-02-28 05:28 UTC
