### ISSUE TITLE
2.3.0 generates PPT file that leads to error dialog in PowerPoint 2011 for Mac (works with 2.2.0)

### ISSUE THREAD

**Issue by ronnyroeller** [gitbrent/PptxGenJS#405] opened 2018-09-18 07:35 UTC
I create a PPT file following the documentation using the latest 2.3.0 release:
```javascript
const PptxGenJS = require("pptxgenjs");

const pptx = new PptxGenJS();
const slide = pptx.addNewSlide();
slide.addText('Hello World!', { x:1.5, y:1.5, fontSize:18, color:'363636' });
pptx.save('Sample Presentation');
```

Running the script generates this file: [Sample Presentation.pptx](https://github.com/gitbrent/PptxGenJS/files/2391617/Sample.Presentation.pptx)

When opening the file in PowerPoint 2011 for Mac, I see the error message "PowerPoint found content in the file Sample Presentation.pptx that it did not understand." (after confirming the dialog, the PPT file loads):

![image](https://user-images.githubusercontent.com/9339055/45671159-082ab200-bb25-11e8-8618-d9afa17f40f5.png)

Here the PowerPoint version:

![image](https://user-images.githubusercontent.com/9339055/45671222-30b2ac00-bb25-11e8-9436-0f0bd564a10f.png)

After downgrading PptxGenJS to 2.2.0 and regenerating the file -> the newly created file can be opened in PowerPoint without any warning.

**Comment by ronnyroeller** [comment] 2018-09-18 08:47
I verified that the file loads without any error dialog in the most recent Office 2016 version for Mac:

![image](https://user-images.githubusercontent.com/9339055/45675709-3a8ddc80-bb30-11e8-9790-53eada8d62a0.png)

**Comment by gitbrent** [comment] 2018-09-19 04:11
Hi @ronnyroeller,

These types of issues with legacy versions are no fun... there's too many code changes between versions to guess what's causing it.

Any way you can diff the two presentations?  (Rename them to .zip, open them and check the slides)

**Comment by ronnyroeller** [comment] 2018-09-19 10:15
> These types of issues with legacy versions are no fun

Just to confirm: It's indeed the legacy version of PowerPoint (2011). But I'm using the latest version of PptxGenJS (2.3.0).
Hence, the PPTs are the same when opening the file in Office 2011 (doesn't work) and Office 2016 (works).

**Comment by gitbrent** [comment] 2018-09-19 23:52
Correct.  I'm saying "legacy" to denote the age of the PPTX processor in those old versions.  They choke on things the newer versions do not.

**Comment by BandaSatish07** [comment] 2018-11-08 16:38
Hi @ronnyroeller,

Did you found any solution for the above error, Me too facing the same issue with PowerPoint Version 2010 in remaining versions it works as expected.
Please find Version Details

![ppt error alert](https://user-images.githubusercontent.com/44244180/48212730-3cdb1d00-e3a2-11e8-82d5-bf1d488a4441.png)

Alert Message which am getting
![erroralert](https://user-images.githubusercontent.com/44244180/48212909-9ba09680-e3a2-11e8-9f24-4f71cb35ac47.png)

Please let me know if you got sorted the issue if not team please help us how to sort the issue.

Thanks

**Comment by gitbrent** [comment] 2018-11-09 04:13
### Help Wanted

I am unable to produce this issue as i have no access to legacy versions, but it should be easy enough to deduce.

Generate a "Hello World" presentation in the older desktop PowerPoint app, then produce one using PptxGenJS.

Open both the files using a zip tool (a PPT is just a zip file with files/directories), then diff the Slide01.xml files... What - other than formatting, etc. - stands out?  Is this a text issue, does it only impact charts??

I'm happy to fix any issues - i'd like to support any/all versions.

**Comment by BandaSatish07** [comment] 2018-11-09 07:51
Hi Team,

Please find two different PPT files generated with pptxgenjs and my version MS office 2010
[pptxgenjsFile.pptx](https://github.com/gitbrent/PptxGenJS/files/2565011/pptxgenjsFile.pptx)
[MSOffice2010.pptx](https://github.com/gitbrent/PptxGenJS/files/2565012/MSOffice2010.pptx)

On xml comparing we found much differences, please help us on this issue

Thanks.

**Comment by restrella2** [comment] 2018-12-11 19:00
i see extra folders in the ppt folder - notesSlides and notesMasters folders are new

**Comment by nymsa** [comment] 2020-01-14 13:15
I may have found a solution.
I compared the generated presentation and the presentation saved after recovery.
The error disappeared when I change order of xml elements in file ppt/presentation.xml
I moved sldIdLst after notesMasterIdLst.
In your file gen-xml.ts adding all Slides is second step, then adding notes master.
May be change their places?

**Comment by gitbrent** [comment] 2020-01-15 05:03
Thanks @nymsa - confirmed by creating a new PPTX on newest desktop PowerPoint.

<img width="501" alt="Screen Shot 2020-01-14 at 23 01 38" src="https://user-images.githubusercontent.com/7218970/72406478-fa3d6f00-3721-11ea-9c51-82cc9c9b6480.png">

**Comment by gitbrent** [comment] 2020-02-28 05:08
[Closing due to age]

**Closed by gitbrent** 2020-02-28 05:08 UTC
Labels: help-wanted, legacy-versions, watchlist

**Comment by kritarth2121** [comment] 2024-02-14 13:59
Increase, the page layout, it worked for me
pptx.defineLayout({ name: 'A3', width: 16, height: 10 });
pptx.layout = 'A3';
