### ISSUE TITLE
Unable to generate powerpoint using node/express

### ISSUE THREAD

**Issue by thollmann** [gitbrent/PptxGenJS#637] opened 2020-01-03 22:32 UTC
Using version 3.0.0

`const pptxgenjs = require('pptxgenjs');`
`const pptx = new pptxgenjs();`

When trying to reference pptx (adding slide, saving/exporting.. etc) I am getting the following error inside of terminal 

ReferenceError: JSZip is not defined
    at Object.<anonymous> (/......./node_modules/pptxgenjs/dist/pptxgen.min.js:2:190018)

**Comment by bestis** [comment] 2020-01-07 13:05
If you didn't already notice, there's also https://github.com/gitbrent/PptxGenJS/issues/638 which is fixed and it works with  https://github.com/gitbrent/PptxGenJS.git#2cee3f0c412106aefb1f87fc16bfef78ae5521a7

**Comment by gitbrent** [comment] 2020-01-08 02:39
Duplicate of Issue #638

**Closed** 2020-01-08 02:39 UTC

**Comment by gitbrent** [comment] 2020-01-08 05:34
Fixed in [Version 3.0.1](https://github.com/gitbrent/PptxGenJS/releases/tag/v3.0.1)
